### ISSUE TITLE
启用插件的时候发生错误，错误信息

### ISSUE THREAD

**Issue by hsu1943** [jjandxa/flarum-ext-chinese-search#1]
启用插件的时候发生错误
debug打开，错误信息：

```
200 OK
POST http://abcd.com/api/extensions/jjandxa-chinese-search

<br />
<b>Parse error</b>:  syntax error, unexpected ':', expecting ';' or '{' in <b>/www/wwwroot/abcd.com/vendor/jjandxa/flarum-ext-chinese-search/src/Utils/XunSearchUtils.php</b> on line <b>17</b><br />
```

运行测试命令
```
./vendor/bin/xs search -p ./vendor/jjandxa/flarum-ext-chinese-search/app.ini -q 关键字
./vendor/bin/xs index -p ./vendor/jjandxa/flarum-ext-chinese-search/app.ini --info
```

出现提示Permission denied
```
./vendor/bin/xs: line 17: /www/wwwroot/abcd.com/vendor/hightman/xunsearch/util/xs: Permission denied
```
环境：
* Flarum v0.1.0-beta.7
* Nginx 1.12
* PHP 5.6.30
* MySql 5.6.37

插件：
```
 "require": {
        "flarum/core": "^0.1.0",
        "flarum/flarum-ext-akismet": "^0.1.0",
        "flarum/flarum-ext-approval": "^0.1.0",
        "flarum/flarum-ext-auth-facebook": "^0.1.0",
        "flarum/flarum-ext-auth-github": "^0.1.0",
        "flarum/flarum-ext-auth-twitter": "^0.1.0",
        "flarum/flarum-ext-bbcode": "^0.1.0",
        "flarum/flarum-ext-emoji": "^0.1.0",
        "flarum/flarum-ext-english": "^0.1.0",
        "flarum/flarum-ext-flags": "^0.1.0",
        "flarum/flarum-ext-likes": "^0.1.0",
        "flarum/flarum-ext-lock": "^0.1.0",
        "flarum/flarum-ext-markdown": "^0.1.0",
        "flarum/flarum-ext-mentions": "^0.1.0",
        "flarum/flarum-ext-pusher": "^0.1.0",
        "flarum/flarum-ext-sticky": "^0.1.0",
        "flarum/flarum-ext-subscriptions": "^0.1.0",
        "flarum/flarum-ext-suspend": "^0.1.0",
        "flarum/flarum-ext-tags": "^0.1.0",
        "csineneo/flarum-ext-simplified-chinese": "v0.1.0-beta.7.2",
        "avatar4eg/flarum-ext-users-list": "^0.1.1",
        "reflar/user-management": "^0.1.4",
        "xengine/flarum-ext-markdown-editor": "^1.3",
        "flagrow/upload": "^0.6.0",
        "zeokat/flarum-ext-seoslugs": "^0.1.1",
        "jjandxa/flarum-ext-chinese-search": "^0.0.3"
    }
```

**Comment by jjandxa** [comment]
看看你 flarum 目录的权限

**Comment by hsu1943** [comment]
## flarum文件夹里面的权限： ##
```
[root@yeyaw vendor]# ls -l flarum
total 76
drwxr-xr-x 11 root root 4096 Dec  1 18:34 core
drwxr-xr-x  6 root root 4096 Dec  1 18:34 flarum-ext-akismet
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-approval
drwxr-xr-x  6 root root 4096 Dec  1 18:34 flarum-ext-auth-facebook
drwxr-xr-x  6 root root 4096 Dec  1 18:34 flarum-ext-auth-github
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-auth-twitter
drwxr-xr-x  3 root root 4096 Dec  1 18:34 flarum-ext-bbcode
drwxr-xr-x  6 root root 4096 Dec  1 18:34 flarum-ext-emoji
drwxr-xr-x  3 root root 4096 Dec  1 18:34 flarum-ext-english
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-flags
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-likes
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-lock
drwxr-xr-x  3 root root 4096 Dec  1 18:34 flarum-ext-markdown
drwxr-xr-x  8 root root 4096 Dec  1 18:34 flarum-ext-mentions
drwxr-xr-x  6 root root 4096 Dec  1 18:34 flarum-ext-pusher
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-sticky
drwxr-xr-x  8 root root 4096 Dec  1 18:34 flarum-ext-subscriptions
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-suspend
drwxr-xr-x  7 root root 4096 Dec  1 18:34 flarum-ext-tags
```

## vendor文件夹的权限： ##
```
[root@yeyaw vendor]# ls -l
total 156
-rw-r--r--  1 root root  178 Dec 13 16:58 autoload.php
drwxr-xr-x  3 root root 4096 Dec  5 15:30 avatar4eg
drwxr-xr-x  2 root root 4096 Dec 13 16:58 bin
drwxr-xr-x  3 root root 4096 Dec  1 18:33 components
drwxr-xr-x  2 root root 4096 Dec 13 16:58 composer
drwxr-xr-x  3 root root 4096 Dec  1 19:39 csineneo
drwxr-xr-x  3 root root 4096 Dec  1 18:33 danielstjules
drwxr-xr-x  3 root root 4096 Dec  1 18:33 dflydev
drwxr-xr-x  9 root root 4096 Dec  1 18:33 doctrine
drwxr-xr-x  3 root root 4096 Dec  1 18:33 filp
drwxr-xr-x  3 root root 4096 Dec 12 14:13 flagrow
drwxr-xr-x 21 root root 4096 Dec  1 18:34 flarum
drwxr-xr-x  4 root root 4096 Dec  1 18:33 franzl
drwxr-xr-x  5 root root 4096 Dec  1 18:33 guzzlehttp
drwxr-xr-x  3 root root 4096 Dec 13 16:58 hightman
drwxr-xr-x  3 root root 4096 Dec  1 18:33 http-interop
drwxr-xr-x 16 root root 4096 Dec  1 18:33 illuminate
drwxr-xr-x  3 root root 4096 Dec  1 18:33 intervention
drwxr-xr-x  4 root root 4096 Dec  1 18:33 ircmaxell
drwxr-xr-x  3 root root 4096 Dec 13 16:58 jjandxa
drwxr-xr-x  7 root root 4096 Dec  1 18:34 league
drwxr-xr-x  4 root root 4096 Dec  1 18:33 matthiasmullie
drwxr-xr-x  3 root root 4096 Dec  1 18:33 monolog
drwxr-xr-x  3 root root 4096 Dec  1 18:33 nesbot
drwxr-xr-x  3 root root 4096 Dec  1 18:33 nikic
drwxr-xr-x  3 root root 4096 Dec  1 18:33 oyejorge
drwxr-xr-x  3 root root 4096 Dec  1 18:33 paragonie
drwxr-xr-x  4 root root 4096 Dec  1 18:33 psr
drwxr-xr-x  3 root root 4096 Dec  1 18:34 pusher
drwxr-xr-x  3 root root 4096 Dec 12 14:13 ramsey
drwxr-xr-x  3 root root 4096 Dec  5 15:53 reflar
drwxr-xr-x  3 root root 4096 Dec  1 18:33 s9e
drwxr-xr-x  3 root root 4096 Dec  1 18:33 swiftmailer
drwxr-xr-x 11 root root 4096 Dec  1 18:33 symfony
drwxr-xr-x  3 root root 4096 Dec  1 18:33 tijsverkoyen
drwxr-xr-x  3 root root 4096 Dec  1 18:33 tobscure
drwxr-xr-x  3 root root 4096 Dec  5 16:00 xengine
drwxr-xr-x  5 root root 4096 Dec  1 18:33 zendframework
drwxr-xr-x  3 root root 4096 Dec 13 15:38 zeokat
```

## jjandxa文件夹的权限： ##
```
[root@yeyaw jjandxa]# ls -l
total 4
drwxr-xr-x 5 root root 4096 Dec 13 16:58 flarum-ext-chinese-search
```

## flarum-ext-chinese-search文件夹的权限： ##
```
[root@yeyaw jjandxa]# ls -l
[root@yeyaw flarum-ext-chinese-search]# ls -l
total 40
-rw-r--r-- 1 root root 11357 Dec 13 16:58 LICENSE
-rw-r--r-- 1 root root    54 Dec 13 16:58 README.md
-rw-r--r-- 1 root root   218 Dec 13 16:58 app.ini
-rw-r--r-- 1 root root  1740 Dec 13 16:58 bootstrap.php
-rw-r--r-- 1 root root   628 Dec 13 16:58 composer.json
drwxr-xr-x 3 root root  4096 Dec 13 16:58 js
drwxr-xr-x 2 root root  4096 Dec 13 16:58 migrations
drwxr-xr-x 5 root root  4096 Dec 13 16:58 src
```

**Comment by jjandxa** [comment]
你整个应用的文件夹最好设置为 www-data 用户与 www-data 用户组。(具体是不是 www-data 需要看你 nginx 里的配置)。
```
sudo chown -R www-data:www-data /www/wwwroot/abcd.com
```

**Comment by jjandxa** [comment]
@hsu1943 是否已解决？

**Comment by hsu1943** [comment]
我看了我的nginx的配置是：
```
user  www www;
```
那么我应该：
```
chown -R www:www /www/wwwroot/abcd.com
```
这样对吗？（环境是centos）
非常感谢你的回复，我还没有试，因为我发现我所有网站内的文件夹和文件的所有者都是root（大概是因为我直接用root登录composer安装的），从上面的ls可以看出来。我担心会搞崩其他程序啥的，运维能力很欠缺。

我安装插件以及flarum都是ssh下root用户用composer安装的，也就是说我的nginx用户www对这些用root安装的文件夹都存在这个问题，这么理解对吗？

但其他的插件都能正常运行，是因为咱们这个插件里的XS需要这个吗？

再次感谢你的回复。

**Comment by jjandxa** [comment]
不太确定，一般来说 nginx 的虚拟主机目录（也就对应到 abcd.com 目录）是需要可供 nginx 配置中的用户读取的。你可以完全 copy 一份 abcd.com 目录作为备份 abcd.com.backup 。然后再更改权限，这样如果需要恢复，只需要删除现有的文件夹，然后将备份的文件夹名称更改回 abcd.com 即可。

**Comment by jjandxa** [comment]
另外，你的问题确实是权限不足。如若还不行，我会使用相同环境进行测试再看结果。

**Comment by hsu1943** [comment]
谢谢你的指导，我在`wwwroot`目录下运行了如下代码
备份：
```
cp -r ./abcd.com ./abcd.com.bak
```
改变文件家归属：
```
chown -R www:www /www/wwwroot/abcd.com
```
查看：
```
[root@yeyaw wwwroot]# ls -l
total 16
drwxr-xr-x 2 www  www  4096 Nov 17 23:20 default
drwxr-xr-x 7 www  www  4096 Dec 11 15:57 abcd.com
drwxr-xr-x 7 root root 4096 Dec 15 17:50 abcd.com.bak
```
然后清除插件缓存和网站缓存，在后台尝试enable插件，报错信息和上面的一样，运行测试，错误信息也一样。

我的网站目录和www用户这些都是在宝塔面板里面添加网站的时候自动添加的，lnmp也是在宝塔面板一键部署的。安装宝塔之前是全新安装的CentOS Linux release 7.2.1511 (Core)版本。

**Comment by vincenth520** [comment]
一样的错误

**Comment by jjandxa** [comment]
找到问题了，出在 xunsearch 官方的 sdk 上。可能是由于他们 composer 包管理器里的版本权限有问题。
你们执行以下命令即可：
```
cd 网站目录
chmod -R 755 ./vendor/hightman/xunsearch
```

**Comment by hsu1943** [comment]
运行了这个
```
chmod -R 755 ./vendor/hightman/xunsearch
```
之后的测试：
```
[root@yeyaw abcd.com]# ./vendor/bin/xs index -p ./vendor/jjandxa/flarum-ext-chinese-search/app.ini --info
[XSException] vendor/hightman/xunsearch/lib/XSServer.class.php(477): Connection refused(C#111, localhost:8383)
#0 vendor/hightman/xunsearch/lib/XSServer.class.php(172): XSServer->connect()
#1 vendor/hightman/xunsearch/lib/XSServer.class.php(147): XSServer->open(8383)
#2 vendor/hightman/xunsearch/lib/XS.class.php(415): XSServer->__construct(8383, Object(XS))
#3 vendor/hightman/xunsearch/lib/XS.class.php(186): XS->getIndex()
#4 Indexer.php(157): XSComponent->__get('index')
#5 xs(26): require('/www/wwwroot/fh...')
#6 {main}
```
开启插件与前面的报错一样，8383/8384端口防火墙已放行

**Comment by jjandxa** [comment]
@hsu1943 是否确定安装了 xunsearch 的服务端
